/*
 * display.cpp — LVGL-based terminal display rendering.
 *
 * SPDX-License-Identifier: MIT
 */

#include "display.h"
#include "terminal.h"
#include "sixel_graphics.h"
#include "serial_transport.h"
#include "ime_ui.h"

#include <inttypes.h>
#include <string.h>
#include <esp_log.h>
#include <esp_heap_caps.h>
#include <freertos/FreeRTOS.h>

#include "lvgl_port.h"
#include "lvgl_port_disp.h"
#include "lvgl_port_touch.h"
#include "lvgl.h"
#include "font/lv_font_fmt_txt.h"

// CJK font declarations (generated by lv_font_conv)
extern "C" const lv_font_t lv_font_cjk_16;
extern "C" const lv_font_t lv_font_cjk_28;

static const char *TAG = "display";

static lv_obj_t   *term_canvas  = NULL;
static lv_obj_t   *status_label = NULL;
static lv_timer_t *cursor_timer = NULL;
static lv_obj_t   *s_visual_bell_overlay = NULL;
static lv_timer_t *s_visual_bell_timer = NULL;
static bool s_japanese_input_active = false;
static bool s_katakana_input_active = false;
// Sized for the maximum row count (Small font: 43 rows)
static lv_obj_t   *row_canvases[TERM_ROWS_MAX]    = {};
static uint8_t    *row_canvas_bufs[TERM_ROWS_MAX] = {};
// Small font uses 43*16 = 688 terminal pixels, leaving a 12-pixel strip
// above the 20-pixel status bar. A dedicated graphics-only canvas keeps the
// advertised 1280x700 Sixel surface visible in that strip.
static lv_obj_t   *sixel_tail_canvas = NULL;
static uint8_t    *sixel_tail_buf = NULL;
static int         sixel_tail_height = 0;
static bool        sixel_tail_was_visible = false;

// LVGL invokes touch event callbacks from its own task.  They only accumulate
// a compact request here; main.cpp owns the terminal state and applies the
// request before calling the normal redraw path.
static portMUX_TYPE s_scrollback_touch_mux = portMUX_INITIALIZER_UNLOCKED;
static int s_scrollback_touch_pending_lines = 0;
static bool s_scrollback_touch_pending_tap = false;
static bool s_scrollback_touch_dragging = false;
static bool s_scrollback_touch_moved = false;
static int s_scrollback_touch_last_y = 0;
static int s_scrollback_touch_accum_y = 0;
static constexpr int TOUCH_TAP_SLOP_PX = 8;
static constexpr int TOUCH_MAX_PENDING_LINES = TERM_SCROLLBACK_MAX_LINES;

static constexpr uint32_t LCD_H_RES = 720;
static constexpr uint32_t LCD_V_RES = 1280;
static lv_display_t *s_lvgl_disp        = nullptr;
static lv_indev_t   *s_lvgl_touch_indev = nullptr;

// Active font pointer — updated by ui_rebuild_for_font_size()
static const lv_font_t *s_active_font = &lv_font_cjk_28;

static constexpr uint32_t VISUAL_BELL_FLASH_MS = 85;

static void visual_bell_timer_cb(lv_timer_t *timer)
{
    if (s_visual_bell_overlay == NULL) return;
    lv_obj_add_flag(s_visual_bell_overlay, LV_OBJ_FLAG_HIDDEN);
    // LVGL timers are periodic. Pausing here makes this an explicit one-shot
    // pulse and avoids waking the display task while no Bell is active.
    lv_timer_pause(timer);
}

static int clamp_touch_pending_lines(int value)
{
    if (value > TOUCH_MAX_PENDING_LINES) return TOUCH_MAX_PENDING_LINES;
    if (value < -TOUCH_MAX_PENDING_LINES) return -TOUCH_MAX_PENDING_LINES;
    return value;
}

static void terminal_touch_event_cb(lv_event_t *event)
{
    lv_indev_t *indev = lv_indev_active();
    if (indev == NULL) return;

    const lv_event_code_t code = lv_event_get_code(event);
    lv_point_t point = {};
    lv_indev_get_point(indev, &point);

    portENTER_CRITICAL(&s_scrollback_touch_mux);
    if (code == LV_EVENT_PRESSED) {
        s_scrollback_touch_dragging = true;
        s_scrollback_touch_moved = false;
        s_scrollback_touch_last_y = point.y;
        s_scrollback_touch_accum_y = 0;
    } else if (code == LV_EVENT_PRESSING && s_scrollback_touch_dragging) {
        const int delta_y = point.y - s_scrollback_touch_last_y;
        s_scrollback_touch_last_y = point.y;
        s_scrollback_touch_accum_y += delta_y;

        const int line_height = TERM_FONT_H > 0 ? TERM_FONT_H : 1;
        int lines = 0;
        while (s_scrollback_touch_accum_y >= line_height) {
            ++lines;
            s_scrollback_touch_accum_y -= line_height;
        }
        while (s_scrollback_touch_accum_y <= -line_height) {
            --lines;
            s_scrollback_touch_accum_y += line_height;
        }
        if (lines != 0) {
            // Downward finger movement moves content down to reveal older
            // rows, therefore positive line counts mean "older".
            s_scrollback_touch_pending_lines = clamp_touch_pending_lines(
                s_scrollback_touch_pending_lines + lines);
            s_scrollback_touch_moved = true;
        }
    } else if (code == LV_EVENT_RELEASED) {
        if (s_scrollback_touch_dragging && !s_scrollback_touch_moved &&
            s_scrollback_touch_accum_y < TOUCH_TAP_SLOP_PX &&
            s_scrollback_touch_accum_y > -TOUCH_TAP_SLOP_PX) {
            s_scrollback_touch_pending_tap = true;
        }
        s_scrollback_touch_dragging = false;
        s_scrollback_touch_moved = false;
        s_scrollback_touch_accum_y = 0;
    } else if (code == LV_EVENT_PRESS_LOST || code == LV_EVENT_INDEV_RESET) {
        s_scrollback_touch_dragging = false;
        s_scrollback_touch_moved = false;
        s_scrollback_touch_accum_y = 0;
    }
    portEXIT_CRITICAL(&s_scrollback_touch_mux);
}

bool display_take_scrollback_touch_request(int *line_delta, bool *tap_to_live)
{
    if (line_delta == NULL || tap_to_live == NULL) return false;

    portENTER_CRITICAL(&s_scrollback_touch_mux);
    *line_delta = s_scrollback_touch_pending_lines;
    *tap_to_live = s_scrollback_touch_pending_tap;
    s_scrollback_touch_pending_lines = 0;
    s_scrollback_touch_pending_tap = false;
    portEXIT_CRITICAL(&s_scrollback_touch_mux);
    return *line_delta != 0 || *tap_to_live;
}

// Draw a single glyph (1bpp fmt_txt) into the row pixel buffer at column offset cx_start.
// cell_width: number of pixel columns to fill (TERM_FONT_W for half-width, TERM_FONT_W*2 for full-width)
static void draw_glyph(uint16_t *buf, int cx_start, int cell_width,
                       const lv_font_t *font, uint32_t letter,
                       uint16_t fg16, uint16_t bg16, int terminal_y,
                       bool composite_sixel)
{
    const lv_font_fmt_txt_dsc_t *fdsc = (const lv_font_fmt_txt_dsc_t *)font->dsc;
    const int stride = LVGL_W;

    // A live terminal image is composited beneath blank text cells. History
    // deliberately has no image plane, and a cursor gets an opaque inverse
    // cell so it remains visible above a graphic.
    if (composite_sixel) {
        sixel_graphics_composite_background(buf + cx_start, stride,
                                            cx_start, terminal_y,
                                            cell_width, TERM_FONT_H, bg16);
    } else {
        for (int y = 0; y < TERM_FONT_H; y++) {
            uint16_t *row_ptr = buf + cx_start + y * stride;
            for (int x = 0; x < cell_width; x++) row_ptr[x] = bg16;
        }
    }

    lv_font_glyph_dsc_t g_dsc;
    bool found = lv_font_get_glyph_dsc(font, &g_dsc, letter, 0);
    if (!found || g_dsc.box_w == 0 || g_dsc.box_h == 0) {
        return;  // background already filled
    }

    uint32_t gid = g_dsc.gid.index;
    const lv_font_fmt_txt_glyph_dsc_t *gdsc = &fdsc->glyph_dsc[gid];
    const uint8_t *bitmap = &fdsc->glyph_bitmap[gdsc->bitmap_index];

    int bw = g_dsc.box_w;
    int bh = g_dsc.box_h;
    int ox = g_dsc.ofs_x;
    int baseline_y   = (TERM_FONT_H - 1) - (int)font->base_line;
    int cell_y_start = baseline_y - (int)g_dsc.ofs_y - bh + 1;

    for (int gy = 0; gy < bh; gy++) {
        int cy = cell_y_start + gy;
        if (cy < 0 || cy >= TERM_FONT_H) continue;
        uint16_t *row_ptr = buf + cx_start + cy * stride;
        for (int gx = 0; gx < bw; gx++) {
            int cx = ox + gx;
            if (cx < 0 || cx >= cell_width) continue;
            int bit_idx  = gy * bw + gx;
            int byte_idx = bit_idx >> 3;
            int bit_pos  = 7 - (bit_idx & 7);
            uint8_t bit  = (bitmap[byte_idx] >> bit_pos) & 1;
            if (bit) row_ptr[cx] = fg16;
        }
    }
}

static void term_rebuild_row(int r)
{
    uint16_t *buf = (uint16_t *)row_canvas_bufs[r];
    if (buf == NULL) return;

    const lv_font_t *font = s_active_font;
    const bool viewing_scrollback = term_scrollback_is_viewing();
    const TermCell *source_row = term_scrollback_display_row(r);
    if (source_row == NULL) return;

    for (int c = 0; c < TERM_COLS; c++) {
        const TermCell *cell = &source_row[c];

        // Skip right-half cells of wide characters (already drawn by left half)
        if (cell->wide == 2) continue;

        bool is_cursor = (!viewing_scrollback && r == cursor_row && c == cursor_col &&
                          cursor_visible && cursor_blink_state);

        uint8_t fg_idx = cell->fg & 15;
        uint8_t bg_idx = cell->bg & 15;
        lv_color_t fg_col = is_cursor ? lv_color_black() : TERM_COLORS[fg_idx];
        lv_color_t bg_col = is_cursor ? lv_color_white() : TERM_COLORS[bg_idx];
        uint16_t fg16 = lv_color_to_u16(fg_col);
        uint16_t bg16 = lv_color_to_u16(bg_col);

        uint32_t cp = cell->codepoint;
        bool is_wide = (cell->wide == 1);
        int cell_width = is_wide ? (TERM_FONT_W * 2) : TERM_FONT_W;
        int cx_start = c * TERM_FONT_W;

        // Clamp to buffer width
        if (cx_start + cell_width > LVGL_W) cell_width = LVGL_W - cx_start;
        if (cx_start >= LVGL_W) continue;

        draw_glyph(buf, cx_start, cell_width, font, cp, fg16, bg16,
                   r * TERM_FONT_H,
                   !viewing_scrollback && !is_cursor && sixel_graphics_has_displayed_pixels());
    }

    // Notify LVGL that the canvas pixel buffer has been updated
    if (row_canvases[r]) {
        lv_canvas_set_buffer(row_canvases[r], row_canvas_bufs[r], LVGL_W, TERM_FONT_H, LV_COLOR_FORMAT_RGB565);
        lv_obj_invalidate(row_canvases[r]);
    }
}

static void sixel_rebuild_tail(bool show_graphics)
{
    if (sixel_tail_canvas == NULL || sixel_tail_buf == NULL || sixel_tail_height <= 0) return;
    if (show_graphics) {
        sixel_graphics_composite_background((uint16_t *)sixel_tail_buf, LVGL_W,
                                            0, TERM_ROWS * TERM_FONT_H,
                                            LVGL_W, sixel_tail_height, 0x0000);
    } else {
        memset(sixel_tail_buf, 0, (size_t)LVGL_W * (size_t)sixel_tail_height * sizeof(uint16_t));
    }
    lv_canvas_set_buffer(sixel_tail_canvas, sixel_tail_buf, LVGL_W,
                         sixel_tail_height, LV_COLOR_FORMAT_RGB565);
    lv_obj_invalidate(sixel_tail_canvas);
}

void term_refresh_display(void)
{
    if (term_canvas == NULL) return;

    static uint32_t rendered_scrollback_generation = UINT32_MAX;
    const bool viewing_scrollback = term_scrollback_is_viewing();
    const uint32_t scrollback_generation = term_scrollback_view_generation();

    // Remote output still updates the live buffer while history is viewed.
    // Do not redraw the frozen transcript for those updates; a drag, clear,
    // or return-to-live increments the view generation and requests a redraw.
    if (viewing_scrollback && rendered_scrollback_generation == scrollback_generation) return;

    static int prev_cursor_row = -1;
    static int prev_cursor_col = -1;
    if (viewing_scrollback) {
        term_mark_all_dirty();
    } else {
        if (prev_cursor_row != cursor_row || prev_cursor_col != cursor_col) {
            term_mark_dirty(prev_cursor_row);
            term_mark_dirty(cursor_row);
            prev_cursor_row = cursor_row;
            prev_cursor_col = cursor_col;
        } else {
            term_mark_dirty(cursor_row);
        }
    }

    lvgl_port_lock(0);
    for (int r = 0; r < TERM_ROWS; r++) {
        if (row_dirty[r]) {
            term_rebuild_row(r);
            row_dirty[r] = false;
        }
    }
    // The tail has no terminal rows and therefore no row_dirty flag. Rebuild
    // it while graphics are live, and once more when the last graphic is
    // cleared, so Small font covers the complete 700-pixel terminal surface.
    const bool sixel_visible = !viewing_scrollback && sixel_graphics_has_displayed_pixels();
    if (sixel_tail_canvas != NULL && (sixel_visible || sixel_tail_was_visible)) {
        sixel_rebuild_tail(sixel_visible);
    }
    sixel_tail_was_visible = sixel_visible;
    lvgl_port_unlock();

    rendered_scrollback_generation = viewing_scrollback ? scrollback_generation : UINT32_MAX;
}

static void term_update_status(const char *msg)
{
    if (status_label == NULL) return;
    lvgl_port_lock(0);
    lv_label_set_text(status_label, msg);
    lvgl_port_unlock();
}

void update_status_bar(void)
{
    char buf[200];
    if (term_scrollback_is_viewing()) {
        snprintf(buf, sizeof(buf),
                 " %s:%s  Baud:%" PRIu32 "  Input:%s  View:-%d/%d  Tap=Live",
                 serial_transport_get_name(),
                 serial_transport_get_status(),
                 serial_transport_get_baud_rate(),
                 !s_japanese_input_active ? "Direct" :
                 (s_katakana_input_active ? "JP-KATA" : "JP-HIRA"),
                 term_scrollback_view_offset(), term_scrollback_history_count());
    } else {
        snprintf(buf, sizeof(buf),
                 " %s:%s  Baud:%" PRIu32 "  Input:%s  ^Alt+C=Clear  ^Alt+S=Settings",
                 serial_transport_get_name(),
                 serial_transport_get_status(),
                 serial_transport_get_baud_rate(),
                 !s_japanese_input_active ? "Direct" :
                 (s_katakana_input_active ? "JP-KATA" : "JP-HIRA"));
    }
    term_update_status(buf);
}

void display_set_japanese_input_mode(bool japanese_active, bool katakana_active)
{
    s_japanese_input_active = japanese_active;
    s_katakana_input_active = japanese_active && katakana_active;
}

void display_trigger_visual_bell(void)
{
    if (s_visual_bell_overlay == NULL || s_visual_bell_timer == NULL) return;

    lvgl_port_lock(0);
    // The overlay is non-clickable, so it cannot steal touch or keyboard
    // routing from an open settings panel or Dictionary Editor. Moving it to
    // the foreground lets BEL remain visible even while such a modal overlay
    // is displayed.
    lv_obj_move_foreground(s_visual_bell_overlay);
    lv_obj_remove_flag(s_visual_bell_overlay, LV_OBJ_FLAG_HIDDEN);
    lv_timer_resume(s_visual_bell_timer);
    lv_timer_reset(s_visual_bell_timer);
    lvgl_port_unlock();
}

static void cursor_blink_cb(lv_timer_t *timer)
{
    (void)timer;
    if (!cursor_visible) {
        cursor_blink_state = false;
        return;
    }
    cursor_blink_state = !cursor_blink_state;
    term_refresh_display();
}

void ui_create(void)
{
    // Select font based on current runtime font height
    s_active_font = (g_term_font_h <= 16) ? &lv_font_cjk_16 : &lv_font_cjk_28;
    ESP_LOGI(TAG, "ui_create: font_h=%d, using %s",
             g_term_font_h, (g_term_font_h <= 16) ? "cjk_16" : "cjk_28");

    lvgl_port_lock(0);

    lv_obj_t *scr = lv_scr_act();
    lv_obj_set_style_bg_color(scr, lv_color_black(), 0);
    lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, 0);
    // Terminal history is rendered from a selected row source; LVGL must not
    // attempt to drag the screen or any terminal canvas itself.
    lv_obj_clear_flag(scr, LV_OBJ_FLAG_SCROLLABLE);

    term_canvas = lv_obj_create(scr);
    lv_obj_set_pos(term_canvas, 0, 0);
    lv_obj_set_size(term_canvas, LVGL_W, LVGL_H - STATUS_BAR_H);
    lv_obj_set_style_bg_color(term_canvas, lv_color_black(), 0);
    lv_obj_set_style_bg_opa(term_canvas, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(term_canvas, 0, 0);
    lv_obj_set_style_pad_all(term_canvas, 0, 0);
    lv_obj_clear_flag(term_canvas, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(term_canvas, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(term_canvas, terminal_touch_event_cb, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(term_canvas, terminal_touch_event_cb, LV_EVENT_PRESSING, NULL);
    lv_obj_add_event_cb(term_canvas, terminal_touch_event_cb, LV_EVENT_RELEASED, NULL);
    lv_obj_add_event_cb(term_canvas, terminal_touch_event_cb, LV_EVENT_PRESS_LOST, NULL);
    lv_obj_add_event_cb(term_canvas, terminal_touch_event_cb, LV_EVENT_INDEV_RESET, NULL);

    for (int r = 0; r < TERM_ROWS; r++) {
        size_t buf_size = LV_CANVAS_BUF_SIZE(LVGL_W, TERM_FONT_H, 16, 4);
        row_canvas_bufs[r] = (uint8_t *)heap_caps_malloc(buf_size, MALLOC_CAP_SPIRAM);
        if (row_canvas_bufs[r] == NULL) {
            ESP_LOGE(TAG, "Failed to allocate canvas buffer for row %d", r);
            continue;
        }
        row_canvases[r] = lv_canvas_create(term_canvas);
        lv_canvas_set_buffer(row_canvases[r], row_canvas_bufs[r], LVGL_W, TERM_FONT_H, LV_COLOR_FORMAT_RGB565);
        lv_obj_set_pos(row_canvases[r], 0, r * TERM_FONT_H);
        lv_obj_set_size(row_canvases[r], LVGL_W, TERM_FONT_H);
        // The parent terminal canvas owns the whole drag.  Individual row
        // canvases deliberately do not become pointer targets while a finger
        // crosses a row boundary.
        lv_obj_clear_flag(row_canvases[r], LV_OBJ_FLAG_CLICKABLE);
        lv_canvas_fill_bg(row_canvases[r], lv_color_black(), LV_OPA_COVER);
        row_dirty[r] = true;
    }

    sixel_tail_height = LVGL_H - STATUS_BAR_H - TERM_ROWS * TERM_FONT_H;
    sixel_tail_was_visible = false;
    if (sixel_tail_height > 0) {
        const size_t tail_buf_size = LV_CANVAS_BUF_SIZE(LVGL_W, sixel_tail_height, 16, 4);
        sixel_tail_buf = (uint8_t *)heap_caps_malloc(tail_buf_size, MALLOC_CAP_SPIRAM);
        if (sixel_tail_buf == NULL) {
            ESP_LOGE(TAG, "Failed to allocate Sixel tail canvas (%d px)", sixel_tail_height);
            sixel_tail_height = 0;
        } else {
            sixel_tail_canvas = lv_canvas_create(term_canvas);
            lv_canvas_set_buffer(sixel_tail_canvas, sixel_tail_buf, LVGL_W,
                                 sixel_tail_height, LV_COLOR_FORMAT_RGB565);
            lv_obj_set_pos(sixel_tail_canvas, 0, TERM_ROWS * TERM_FONT_H);
            lv_obj_set_size(sixel_tail_canvas, LVGL_W, sixel_tail_height);
            lv_obj_clear_flag(sixel_tail_canvas, LV_OBJ_FLAG_CLICKABLE);
            lv_canvas_fill_bg(sixel_tail_canvas, lv_color_black(), LV_OPA_COVER);
        }
    }

    // Status bar uses ASCII-only font (lv_font_unscii_16) for compact display
    status_label = lv_label_create(scr);
    lv_obj_set_style_text_font(status_label, &lv_font_unscii_16, 0);
    lv_obj_set_style_text_color(status_label, lv_color_make(0, 0, 0), 0);
    lv_obj_set_style_bg_color(status_label, lv_color_make(0, 200, 0), 0);
    lv_obj_set_style_bg_opa(status_label, LV_OPA_COVER, 0);
    lv_obj_set_pos(status_label, 0, LVGL_H - STATUS_BAR_H);
    lv_obj_set_size(status_label, LVGL_W, STATUS_BAR_H);
    lv_label_set_text(status_label, " TAB5 Serial Terminal - Initializing...");

    // Keep visual Bell independent of the terminal canvases. It neither
    // touches terminal state nor causes a full redraw of the MIPI-DSI surface.
    s_visual_bell_overlay = lv_obj_create(scr);
    lv_obj_set_size(s_visual_bell_overlay, LVGL_W, LVGL_H - STATUS_BAR_H);
    lv_obj_set_pos(s_visual_bell_overlay, 0, 0);
    lv_obj_set_style_bg_color(s_visual_bell_overlay, lv_color_white(), 0);
    lv_obj_set_style_bg_opa(s_visual_bell_overlay, LV_OPA_70, 0);
    lv_obj_set_style_border_width(s_visual_bell_overlay, 0, 0);
    lv_obj_set_style_pad_all(s_visual_bell_overlay, 0, 0);
    lv_obj_clear_flag(s_visual_bell_overlay, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(s_visual_bell_overlay, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(s_visual_bell_overlay, LV_OBJ_FLAG_HIDDEN);

    cursor_timer = lv_timer_create(cursor_blink_cb, 500, NULL);
    s_visual_bell_timer = lv_timer_create(visual_bell_timer_cb, VISUAL_BELL_FLASH_MS, NULL);
    lv_timer_pause(s_visual_bell_timer);

    lvgl_port_unlock();
}

void ui_destroy(void)
{
    lvgl_port_lock(0);

    // Stop and delete cursor blink timer
    if (cursor_timer) {
        lv_timer_delete(cursor_timer);
        cursor_timer = NULL;
    }
    if (s_visual_bell_timer) {
        lv_timer_delete(s_visual_bell_timer);
        s_visual_bell_timer = NULL;
    }

    // Free row canvas pixel buffers
    for (int r = 0; r < TERM_ROWS_MAX; r++) {
        if (row_canvas_bufs[r]) {
            heap_caps_free(row_canvas_bufs[r]);
            row_canvas_bufs[r] = NULL;
        }
        row_canvases[r] = NULL;  // deleted when term_canvas is deleted below
    }

    if (sixel_tail_buf) {
        heap_caps_free(sixel_tail_buf);
        sixel_tail_buf = NULL;
    }
    sixel_tail_canvas = NULL;  // deleted with term_canvas
    sixel_tail_height = 0;
    sixel_tail_was_visible = false;

    // Delete terminal canvas container (also deletes all child row_canvases)
    if (term_canvas) {
        lv_obj_delete(term_canvas);
        term_canvas = NULL;
    }

    // Delete status label
    if (status_label) {
        lv_obj_delete(status_label);
        status_label = NULL;
    }
    if (s_visual_bell_overlay) {
        lv_obj_delete(s_visual_bell_overlay);
        s_visual_bell_overlay = NULL;
    }

    lvgl_port_unlock();
}

void ui_rebuild_for_font_size(int font_w, int font_h)
{
    ESP_LOGI(TAG, "Rebuilding UI for font size %dx%d", font_w, font_h);

    // Select the appropriate font pointer
    if (font_h <= 16) {
        s_active_font = &lv_font_cjk_16;
    } else {
        s_active_font = &lv_font_cjk_28;
    }

    // Remove any preedit/candidate overlay before its LVGL parent objects are
    // destroyed and recreated for the new terminal font geometry.
    ime_ui_hide();

    // Update terminal geometry variables
    term_set_font_size(font_w, font_h);

    // Destroy existing LVGL objects
    ui_destroy();

    // Clear terminal buffer and reset cursor
    term_clear_all();

    // Recreate LVGL objects with new dimensions
    ui_create();

    ESP_LOGI(TAG, "UI rebuilt: %d cols x %d rows", TERM_COLS, TERM_ROWS);
}

esp_err_t app_lcd_lvgl_init(m5::tab5::m5tab5_component &board)
{
    if (s_lvgl_disp != nullptr) return ESP_OK;

    esp_lcd_panel_handle_t panel_handle = board.lcd_panel();
    if (panel_handle == nullptr) {
        ESP_LOGE(TAG, "LCD panel handle unavailable");
        return ESP_ERR_INVALID_STATE;
    }

    lvgl_port_cfg_t lvgl_cfg   = {};
    lvgl_cfg.task_priority     = 6;
    lvgl_cfg.task_stack        = 16384;
    lvgl_cfg.task_affinity     = 1;
    lvgl_cfg.task_max_sleep_ms = 500;
    lvgl_cfg.timer_period_ms   = 5;

    esp_err_t ret = lvgl_port_init(&lvgl_cfg);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "LVGL port init failed: %s", esp_err_to_name(ret));
        return ret;
    }

    lvgl_disp_cfg_t disp_cfg    = {};
    disp_cfg.panel_handle       = panel_handle;
    disp_cfg.hres               = LCD_H_RES;
    disp_cfg.vres               = LCD_V_RES;
    disp_cfg.buffer_size        = LCD_H_RES * LCD_V_RES;
    disp_cfg.color_format       = LV_COLOR_FORMAT_RGB565;
    disp_cfg.flags.full_refresh = 0;
    disp_cfg.flags.direct_mode  = 1;
    disp_cfg.flags.buff_spiram  = 1;
    disp_cfg.flags.sw_rotate    = 1;

    lvgl_disp_dsi_cfg_t dsi_cfg = {};
    dsi_cfg.sw_rotation         = LV_DISPLAY_ROTATION_90;
    dsi_cfg.flags.avoid_tearing = 1;
    dsi_cfg.flags.use_ppa       = 1;

    s_lvgl_disp = lvgl_port_add_disp_dsi(&disp_cfg, &dsi_cfg);
    if (s_lvgl_disp == nullptr) {
        ESP_LOGE(TAG, "Failed to add LVGL DSI display");
        return ESP_FAIL;
    }

    esp_lcd_touch_handle_t touch_handle = board.touch_panel();
    if (touch_handle != nullptr) {
        lvgl_touch_cfg_t touch_cfg = {};
        touch_cfg.disp             = s_lvgl_disp;
        touch_cfg.handle           = touch_handle;
        s_lvgl_touch_indev = lvgl_port_add_touch(&touch_cfg);
        if (s_lvgl_touch_indev) {
            lvgl_port_set_touch_rotation(s_lvgl_touch_indev, LV_DISPLAY_ROTATION_90);
        }
    }

    return ESP_OK;
}
